### ISSUE TITLE
Multiple Answers Using Pipe Not Working

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/LIKHA#3]
Salut! I found that multiple answers using pipes are not yet recognized by UsbongKit.
For example, in the following code snippet...

```
    <task-node name="textFieldWithAnswer~@audioName=question3~3. How do you read these kanji characters (紙, 髪, 神)?Answer=kami|Kami|かみ|カミ">
        <transition to="imageTextDisplay~correct~@audioName=correct~Correct!{br}Yes, the correct answer is: かみ, カミ, kami." name="Yes"></transition>
        <transition to="imageTextDisplay~incorrect~@audioName=incorrect~3~Incorrect!{br}The correct answer is: かみ, カミ, kami." name="No"></transition>   
    </task-node>    
```

The answer could be any of these four, delimited by the pipe, i.e. "|".
`kami|Kami|かみ|カミ`

However, what happens right now in UsbongKit (iOS) is that to get the correct answer, I have to put everything, i.e. `kami|Kami|かみ|カミ`.

Any suggestions on how I may be able to resolve this?

Merci beaucoup!

**Comment by chrisamanse** [comment]
Here's the part of the code in UsbongKit where it checks if it matches the input string with the given answer in the task-node:

``` swift
if textInputTypeNode.textInput == currentTargetTextInput {
  return "Yes"
} else {
  return "No"
}
```

Found in: https://github.com/usbong/UsbongKit/blob/master/UsbongKit/Usbong/UsbongTree/UsbongTree.swift#L107

Thus, if there was `|` delimiter for the string, separate the string into components separated by the delimiter. `String` has a built-in function for this: `myString.componentsSeparatedString(myDelimiter)`, which returns an array. For example:

``` swift
let string = "kami|Kami|かみ|カミ"
let answers = string.componentsSeparatedByString("|")
// answers = ["kami", "Kami", "かみ", "カミ"]
```

Additionally, `Array` has a function `contains(_ element: Element) -> Bool`, which checks if the array contains an element.

Thus, the code in line 107 in `UsbongKit/UsbongKit/Usbong/UsbongTree/UsbongTree.swift` should be:

```
if currentTargetTextInput.componentsSeparatedByString("|").contains(textInputTypeNode.textInput) {
```

You can test the sample code here: http://swiftlang.ng.bluemix.net/#/repl/5808a056ffed3d1242d6a738

**Comment by masarapmabuhay** [comment]
Merci beaucoup pour ta réponse! I encountered the following error though.

<img width="798" alt="screen shot 2016-10-20 at 8 47 28 pm" src="https://cloud.githubusercontent.com/assets/344066/19560415/fe17be5a-9706-11e6-8f42-4a021185e882.png">

The solution was to add "!" after  `currentTargetTextInput`

`if currentTargetTextInput!.componentsSeparatedByString("|").contains(textInputTypeNode.textInput) 
`

I am not too sure why this is so. Tu sais pourquoi?

**Comment by chrisamanse** [comment]
Apologies, `currentTargetTextInput` is of type `String?` (Optional String or `Optional<String>`), which means it can be `nil`. More about optionals: http://stackoverflow.com/questions/24003642/what-is-an-optional-value-in-swift

Thus, it has to be "unwrapped". Appending "!" means we're sure that it's not empty (not `nil`). If the value nil, the app will crash, thus it's safer to use "?". More about optional chainging: http://stackoverflow.com/questions/32775814/swift-optional-chaining

I'll push an update to fix this.

**Comment by masarapmabuhay** [comment]
Je comprends. Merci beaucoup encore une fois!
