### ISSUE TITLE
No "Speak" Button in the "More" Menu

### ISSUE THREAD

**Issue by masarapmabuhay** [usbong/LIKHA#4]
Salut! I noticed that if I wanted to have the app read again for me the text on the screen aloud, I would have to press "More", "Speech Off", and then "Speech On". This means that it takes me three steps to get the app to read the text aloud.

<img width="310" alt="screen shot 2016-10-20 at 9 03 38 pm" src="https://cloud.githubusercontent.com/assets/344066/19560955/3e7f634c-9709-11e6-962e-7661f6df60a8.png">

Perhaps, it would be better if it's something like in UsbongKit (Android)?
<img width="310" alt="sunshinesettings" src="https://cloud.githubusercontent.com/assets/344066/19561143/f39814ae-9709-11e6-9e43-19a6058bd50a.png">

Please let me know if there is something already like this in UsbongKit (iOS), but I just didn't notice.

Merci beaucoup toujours!

**Comment by chrisamanse** [comment]
Thanks for reporting this issue. I agree, we'd have to place a "Speak" option. I'll move the issue to the UsbongKit repo.

**Comment by masarapmabuhay** [comment]
Merci beaucoup! Cordialement!

**Comment by masarapmabuhay** [comment]
This issue is already resolved via [Add "Speak" button #18](https://github.com/usbong/UsbongKit/issues/18). Merci!
